name: demo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.actor }}
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: webserver
      - uses: alonch/actions-aws-website@13496d41c69dbd53ddaa28e5a9e4ed05674bb05b
        with:
          domain: gha-webserver.dev.realsense.ca
          content-path: samples/app/public/
      - uses: alonch/actions-aws-auth@main
        with: 
          name: webserver
          domain: gha-webserver.dev.realsense.ca
      # - uses: alonch/actions-aws-image@main
      #   id: image
      #   with: 
      #     name: webserver
      #     docker-path: samples/app/
      - uses: alonch/actions-aws-webserver@main
        with: 
          name: webserver
          port: 8283
          # action: delete
          domain: gha-webserver.dev.realsense.ca
          container-image: letta/letta:latest
          